# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter m51,$(TARGET_DEVICE)),)

endif
